# Landlab Synthetic NetCDF Builder

<img src="https://www.washington.edu/brand/files/2014/09/W-Logo_Purple_Hex.png" style="float:right;width:200px;padding:20px">   


<br />
This Jupyter Notebook runs the Landlab LandslideProbability component on a synthetic 
Landlab grid using four depth to water table options to replace recharge options described in the paper: <br />
#### Strauch et al. 2018. A hydro-climatological approach to predicting regional landslide probability using Landlab. Earth Surface Dynamics, 6, 1-26. <br /> 
This notebook performs the following functions:<br >
* Import libraries and set HydroShare variables<br />
* Create a grid and data fields used to calculate landslide probability<br />
* Specify Depth to Water Table Distributions to compare four options<br /> 
* Run LandslideProbability function from Landlab landslide component<br /> 
* Compare the sensitivity based on four Depth to Water Table options<br /> 


In [1]:
import landslide_probability
from landslide_probability_20191122 import LandslideProbability
from landlab import RasterModelGrid
from landlab import imshow_grid_at_node

from landlab.io.netcdf import read_netcdf
from landlab.io.netcdf import write_netcdf

import numpy as np


You are not going crazy...
You are not going crazy...


In [2]:
grid = RasterModelGrid((5, 4))

In [3]:
grid.shape == (5, 4)

True

In [4]:
grid.nodes

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [5]:
n=50
gridnodes = grid.number_of_nodes
grid_size = grid.number_of_nodes

Demin_value = 2 
Demax_value = 5
distribution1 = 'uniform'
depth_dist = np.random.uniform(Demin_value, Demax_value,size=n)
print('Depth to water table distribution')
print(depth_dist)

mean_depth=np.mean(depth_dist)
grid['node']['soil__mean_watertable_depth']=mean_depth* np.ones(gridnodes)

print('Mean depth to water table from uniform distribution')
print(mean_depth)
print('Mean Depth to water table - uniform for all nodes')
print(grid['node']['soil__mean_watertable_depth'])

Depth to water table distribution
[ 4.69350994  3.20415646  2.62465206  4.54397354  3.48022977  3.45312326
  3.90158968  4.81969348  3.70981144  4.61658193  3.82312499  2.90498239
  2.30884338  2.79697174  3.70435845  3.98199314  2.12802672  3.25203122
  2.19771935  3.65390948  2.57793329  3.68851869  2.56468458  2.78586244
  4.99079676  4.35755166  4.95945479  2.06392802  2.09348507  4.75841298
  4.39066809  2.47170289  3.65454782  4.58616062  2.65949229  3.57767202
  3.69853272  2.09027843  2.92655412  4.48980182  2.48195754  3.40829814
  3.99160283  4.54608216  3.03513384  2.85540956  2.36982908  4.9793298
  3.15596835  2.74555619]
Mean depth to water table from uniform distribution
3.45508978015
Mean Depth to water table - uniform for all nodes
[ 3.45508978  3.45508978  3.45508978  3.45508978  3.45508978  3.45508978
  3.45508978  3.45508978  3.45508978  3.45508978  3.45508978  3.45508978
  3.45508978  3.45508978  3.45508978  3.45508978  3.45508978  3.45508978
  3.45508978  3.455089

In [6]:
grid.dy, grid.dx

(1.0, 1.0)

In [7]:
list(grid.at_node.keys())

['soil__mean_watertable_depth']

In [8]:
grid.at_node['soil__mean_watertable_depth']

array([ 3.45508978,  3.45508978,  3.45508978,  3.45508978,  3.45508978,
        3.45508978,  3.45508978,  3.45508978,  3.45508978,  3.45508978,
        3.45508978,  3.45508978,  3.45508978,  3.45508978,  3.45508978,
        3.45508978,  3.45508978,  3.45508978,  3.45508978,  3.45508978])

In [9]:
write_netcdf('synthetic_depth.nc', grid, format='NETCDF3_64BIT', names='soil__mean_watertable_depth')

### Add distribution to Landlab grid as array on each node

In [10]:
grid_size


20

In [11]:
grid.nodes

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [12]:

YR1=np.random.uniform(Demin_value, Demax_value,size=grid_size)
YR2=np.random.uniform(Demin_value, Demax_value,size=grid_size)
YR3=np.random.uniform(Demin_value, Demax_value,size=grid_size)
grid['node']['YR1']=YR1
grid['node']['YR2']=YR2
grid['node']['YR3']=YR3


In [13]:
YR1

array([ 3.13488552,  4.36410555,  4.99973639,  3.94802869,  3.84870407,
        4.17646011,  3.99384947,  4.20261474,  4.11634548,  4.62152697,
        3.77404251,  2.73594644,  4.90405298,  2.01495659,  3.44230209,
        4.47111378,  4.26630122,  4.34075039,  4.26890576,  2.64262339])

## 

In [14]:
YR2

array([ 2.13390289,  3.38396202,  4.49874119,  2.0076804 ,  2.48373836,
        2.3597464 ,  4.95045476,  4.88031425,  3.74695112,  2.70990284,
        2.07829949,  2.8233773 ,  4.79713565,  3.54701044,  3.77444712,
        4.19256823,  3.97626778,  4.91193888,  4.82822549,  2.83152669])

In [15]:
YR3

array([ 4.22984935,  4.48220023,  3.88920475,  4.31437155,  2.39899454,
        3.86995565,  3.13621333,  2.98487845,  2.1198065 ,  4.82910215,
        3.83242049,  4.82402074,  2.68930296,  2.70426679,  2.02712749,
        2.16449311,  4.35399719,  2.58800437,  4.00769493,  2.54529527])

In [16]:
grid.at_node.keys()

['YR1', 'YR2', 'YR3', 'soil__mean_watertable_depth']

In [22]:
key=np.arange(grid_size)

In [47]:
HSD_dict_annualmaxDWT=zip(grid['node']['YR1'],grid['node']['YR2'],grid['node']['YR3'])
i=1
for i in range(grid.number_of_nodes):
    HSD_dict_annualmaxDWT[i] = {key[i]:HSD_dict_annualmaxDWT[i]} 

print(HSD_dict_annualmaxDWT)

[{0: (3.1348855160345486, 2.1339028896492409, 4.2298493546765314)}, {1: (4.3641055473531214, 3.3839620238107222, 4.4822002297488588)}, {2: (4.9997363861010431, 4.4987411920372287, 3.8892047488581669)}, {3: (3.9480286943080589, 2.007680398674899, 4.3143715531551994)}, {4: (3.8487040702022735, 2.48373836203718, 2.3989945374607911)}, {5: (4.176460110679832, 2.3597464046292518, 3.86995565015072)}, {6: (3.9938494706376044, 4.9504547555157892, 3.1362133315826775)}, {7: (4.2026147447657127, 4.8803142543445528, 2.9848784481643795)}, {8: (4.1163454826398613, 3.746951123011975, 2.1198065039185501)}, {9: (4.6215269665299221, 2.7099028438244708, 4.829102153571891)}, {10: (3.7740425056733122, 2.0782994936051171, 3.8324204869673371)}, {11: (2.7359464420021391, 2.8233773035209206, 4.8240207409403384)}, {12: (4.9040529801858987, 4.7971356536503436, 2.6893029622097657)}, {13: (2.0149565917571559, 3.5470104394242314, 2.7042667872425739)}, {14: (3.4423020872620453, 3.7744471204150347, 2.0271274892017592)

In [19]:
write_netcdf('synthetic_data_driven_spatial_depth.nc', grid, format='NETCDF3_64BIT', names=['YR1','YR2','YR3'])

In [48]:
read_netcdf('dtw_historic_with_dates_netcdf3.nc')

AttributeError: 'netcdf_variable' object has no attribute 'units'